// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv517bDpa4uLrIDtsfdzqUOGn-pFmP2lU',
    appId: '1:1021779013330:web:73761b987d4e7ba1d4070b',
    messagingSenderId: '1021779013330',
    projectId: 'dorandoran-374312',
    authDomain: 'dorandoran-374312.firebaseapp.com',
    storageBucket: 'dorandoran-374312.appspot.com',
    measurementId: 'G-KWLYM6JSSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDycxonDuGb05IHFu4Gb3Iuk6Btkew6h4A',
    appId: '1:1021779013330:android:f1bf6a84d8ed82bcd4070b',
    messagingSenderId: '1021779013330',
    projectId: 'dorandoran-374312',
    storageBucket: 'dorandoran-374312.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpkcmLGSpc_FQVyHCNbjqa_Eixa8K7g0c',
    appId: '1:1021779013330:ios:be8c61e621ad2805d4070b',
    messagingSenderId: '1021779013330',
    projectId: 'dorandoran-374312',
    storageBucket: 'dorandoran-374312.appspot.com',
    iosClientId: '1021779013330-2sbirvp3rpvtsk5f6tofd7rk62rnk779.apps.googleusercontent.com',
    iosBundleId: 'com.example.dorandoran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpkcmLGSpc_FQVyHCNbjqa_Eixa8K7g0c',
    appId: '1:1021779013330:ios:be8c61e621ad2805d4070b',
    messagingSenderId: '1021779013330',
    projectId: 'dorandoran-374312',
    storageBucket: 'dorandoran-374312.appspot.com',
    iosClientId: '1021779013330-2sbirvp3rpvtsk5f6tofd7rk62rnk779.apps.googleusercontent.com',
    iosBundleId: 'com.example.dorandoran',
  );
}
