spring:
  profiles:
    active: local
---
#profile and DataBase
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ENC(prmDG7wmy6YZGHAMr+IQiqQRYKOQ/fvy2XiIz7endPsJ1ywly3YUxRkMlt3tatuvMJYrFvdjBK50XSY0vXui8iLE6lambM2Pis9fiqZbrnR5zF57Y6AccOX42hAk9VA2)
    username: ENC(Xh/N3MbBIY77cqVSWycSkA==)
    password: ENC(9SMvXdMtykmQ50kPhY8EBPJ0n8XXMFY1)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

#    properties:
#      hibernate:
#        format_sql: true

#    show-sql: true
    hibernate:
      ddl-auto: create

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
      resolve-lazily: true

#  cache:
#    type: redis
#    redis:
#      cache-null-values: true # null 캐싱 여부
#      host: localhost
#      port: 6379

#servlet default encoding UTF-8
server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12 #When deploying to the main server, put / in front of the path
    key-store-password: ENC(dJPMSD5guRWh1po42D2XaU9BGubuo9Zo)
  tomcat:
    mbeanregistry:
      enabled: true
    max-keep-alive-requests: 1

  servlet:
    encoding:
      force: true
  port: 8443

#linux server path
background:
  Store:
#        path: ENC(9QEeqickxWCf+Y92WqaPrsgC1Js2Jm1vL73jNTghzN/D41hISXlJIoFU8Ohh06TMG9PkAdCyEOQ=)
    path: ENC(j8XH8sd8zNSI1/ErDS+ZtyB8zehJjU1Likf0cZMZjHgkcRw/XrEUGtFRDf5LtRsAxs0dLPrT4I4=)

  cnt: 100

userUpload:
  Store:
#    path: ENC(JJQ2tG4BK3GI7HbgLiRCWrbTVBWwg4gujQlV1jb//1ngnOJ4KHP+NaSNrLtJpxyXAPx+5le56F4=)
    path: ENC(m7Iwcgs8PSaRROCO1mjBujx8eZ9CwGZTERbfHK4FNn2axv3F785G9wEfdpcmi+52upZ7wFyY2Cw=)



#IP Adress
doran:
  ip:
#    address: ENC(xBptybqPuMrjKGjysoZ4hmVqKrZXHzmw)
    address: ENC(+aE9NCPvIuPsUCQ4mXMqDUWGf1In44DA+xSotcY87p4=)

#Jasypt
jasypt:
  encryptor:
    bean: jasyptEncryptor

#JWT
jwt:
  issuer: jw1010110@gmail.com
  secret_key: ENC(KJvpOG9KEjdJK9rMuM7Y1no5EAKDlJZ+iQqU29ToVbAlx7oMvi4jBNQ1e5yZqyYZCAzvERYcxaA9+ovAMkw8OpKY6kW6oWRM)

#Actuator
management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    git:
      mode: full

  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  server:
    port: 8079


#log level
#logging:
#  slack:
#    webhook-uri: https://hooks.slack.com/services/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
#    config: classpath:logback-spring.xml


