spring:
  profiles:
    active: local
---
#profile and DataBase
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ENC(iycghWLUzO5YOb9pfckwEhcAoUYxOgl4OQZ7TdY2as4M8tsppVFO+t9WG/8rfnKoRyCx5rwilFQJTL6oe00vZNCYZ51ArMLwwmcbq7/TxVvDe3xPXf+rMBVsOzb7TpE98nkBADBVPR/0N2itGTwD8yo4TEMZS74LIxUWCw8HPeeIVSwKcXELQToHXD+V34hhM3zedNmVMcONvrtqEhtZoA==)
    username: ENC(bfSpttKshL1tH9oM3yw1zg==)
    password: ENC(Tba6cvQrolFasjqUKKQmCC37X4638goacBdr83l70Aw=)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

#    properties:
#      hibernate:
#        format_sql: true

#    show-sql: true
    hibernate:
      ddl-auto: create

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
      resolve-lazily: true

#  cache:
#    type: redis
#    redis:
#      cache-null-values: true # null 캐싱 여부
#      host: localhost
#      port: 6379

#servlet default encoding UTF-8
server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12 #When deploying to the main server, put / in front of the path
    key-store-password: ENC(dJPMSD5guRWh1po42D2XaU9BGubuo9Zo)
  tomcat:
    mbeanregistry:
      enabled: true
    max-keep-alive-requests: 1

  servlet:
    encoding:
      force: true
  port: 8443

#linux server path
background:
  Store:
#        path: ENC(9QEeqickxWCf+Y92WqaPrsgC1Js2Jm1vL73jNTghzN/D41hISXlJIoFU8Ohh06TMG9PkAdCyEOQ=)
    path: ENC(UPnrZF2CEZOCWak/NAFpvOJThksXY9bMIaiB+02IkXcGUz84g7MGWGcRpY+NgRW+Rc8+se68qm05Z1OEpqJYVY+Qi7U7aVogXyGRV0ihuXo=)

  cnt: 100

userUpload:
  Store:
#    path: ENC(JJQ2tG4BK3GI7HbgLiRCWrbTVBWwg4gujQlV1jb//1ngnOJ4KHP+NaSNrLtJpxyXAPx+5le56F4=)
    path: ENC(6U8Gq0k+6o4ucPE3NV2+wuGOHJNFm+RvRHtT0oxFzzUKj9laO0RsnWU8RE9HiWI/5qwLK0NA6HQ2wxLlmHTtLr40j19oluTznJOBor5O+OY=)



#IP Adress
doran:
  ip:
#    address: ENC(xBptybqPuMrjKGjysoZ4hmVqKrZXHzmw)
    address: ENC(+aE9NCPvIuPsUCQ4mXMqDUWGf1In44DA+xSotcY87p4=)

#Jasypt
jasypt:
  encryptor:
    bean: jasyptEncryptor

#JWT
jwt:
  issuer: jw1010110@gmail.com
  secret_key: ENC(KJvpOG9KEjdJK9rMuM7Y1no5EAKDlJZ+iQqU29ToVbAlx7oMvi4jBNQ1e5yZqyYZCAzvERYcxaA9+ovAMkw8OpKY6kW6oWRM)

#Actuator
management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    git:
      mode: full

  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  server:
    port: 8079


#log level
#logging:
#  slack:
#    webhook-uri: https://hooks.slack.com/services/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
#    config: classpath:logback-spring.xml

cloud:
  aws:
    s3:
      bucket: doran-s3-demo
    credentials:
      instance-profile: false
      access-key: ENC(feoY8QffFIvSHNDEjllCz+9ALdpVFNaczbxzTRA2b0k=)
      secret-key: ENC(wW8VJ0VUDMODMlwyIZCv9zPr/U1QQ/T/oaBJjpFACCdoz9Olfs3eCUXFZDu20aGn3U7owu4nSoU=)
    region:
      auto: false
      static: ap-northeast-2
    stack:
      auto: false