#DataBase url
spring:
  datasource:
    url: ENC(prmDG7wmy6YZGHAMr+IQiqQRYKOQ/fvy2XiIz7endPsJ1ywly3YUxRkMlt3tatuvMJYrFvdjBK50XSY0vXui8iLE6lambM2Pis9fiqZbrnR5zF57Y6AccOX42hAk9VA2)
    username: ENC(Xh/N3MbBIY77cqVSWycSkA==)
    password: ENC(9SMvXdMtykmQ50kPhY8EBPJ0n8XXMFY1)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

#    properties:
#      hibernate:
#        format_sql: true

#    show-sql: true
    hibernate:
      ddl-auto: create

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
      resolve-lazily: true

#  cache:
#    type: redis
#    redis:
#      cache-null-values: true # null 캐싱 여부
#      host: localhost
#      port: 6379

#servlet default encoding UTF-8
server:
  tomcat:
    mbeanregistry:
      enabled: true
  servlet:
    encoding:
      force: true

#linux server path
background:
  Store:
    #    path: ENC(9QEeqickxWCf+Y92WqaPrsgC1Js2Jm1vL73jNTghzN/D41hISXlJIoFU8Ohh06TMG9PkAdCyEOQ=)
    path: ENC(vm33s+bW57q2aASSsHWJ61tpYy6z72Z5FC8mPT9UdlpXLp2nnNR7hqkkiuhxFMbDnLlzB6U/a98=)

  cnt: 100

userUpload:
  Store:
#    path: ENC(JJQ2tG4BK3GI7HbgLiRCWrbTVBWwg4gujQlV1jb//1ngnOJ4KHP+NaSNrLtJpxyXAPx+5le56F4=)
    path: ENC(pFd00vtw9cVMwmCR2l4FqK1WXzP5/S8pwo4TqbmTOPz+xiCOMxZaxbB2x2/O2lsqB5ALQeujPEM=)



#IP Adress
doran:
  ip:
#    address: ENC(xBptybqPuMrjKGjysoZ4hmVqKrZXHzmw)
    address: ENC(LDVBP221M7WuHBE9SADZP4VGgsYHwAWH)

#Jasypt
jasypt:
  encryptor:
    bean: jasyptEncryptor

#JWT
jwt:
  issuer: jw1010110@gmail.com
  secret_key: ENC(KJvpOG9KEjdJK9rMuM7Y1no5EAKDlJZ+iQqU29ToVbAlx7oMvi4jBNQ1e5yZqyYZCAzvERYcxaA9+ovAMkw8OpKY6kW6oWRM)

#Actuator
management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    git:
      mode: full

  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always


#log level
logging:
  level:
    com:
      dorandoran: debug
  slack:
    webhook-uri: https://hooks.slack.com/services/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
    config: classpath:logback-spring.xml


