name: DoranServerCI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ${{secrets.working_directory}}

      - name: Build with Gradle
        run: ./gradlew build -x test
        working-directory: ${{secrets.working_directory}}

      - name: Copy JAR file to deployment server
        uses: appleboy/scp-action@7af00892de6f8397c5c3393cfb3b32ae7f91b94b
        with:
          host: ${{ secrets.DEPLOYMENT_SERVER_HOST }}
          username: ${{ secrets.DEPLOYMENT_SERVER_USERNAME }}
          password: ${{ secrets.DEPLOYMENT_SERVER_PASSWORD }}
          port: ${{ secrets.DEPLOYMENT_SERVER_PORT }}
          source: 'doranserver/build/libs/*.jar'
          target: '/DoranDoranWorkflow/doranserver/build/libs/'
          overwrite: true

      - name: Execute deployment script on server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOYMENT_SERVER_HOST }}
          username: ${{ secrets.DEPLOYMENT_SERVER_USERNAME }}
          password: ${{ secrets.DEPLOYMENT_SERVER_PASSWORD }}
          port: ${{ secrets.DEPLOYMENT_SERVER_PORT }}
          script: |
            cd /DoranDoran/doranserver/build/libs
            java -jar -Djasypt.encryptor.password=${{secrets.jasypt_encryptor_password}} *.jar
